### ISSUE TITLE
Couldn't build

### ISSUE THREAD

**Issue by Edeleiz** [splhack/Hello-LWF-Cocos2d-x#4]
I've got this error in VS2013: D:\Work\cocos\Hello-LWF-Cocos2d-x\lwf\project.win32\libLwf.vcxproj : error  : Project "D:\Work\cocos\Hello-LWF-Cocos2d-x\lwf\project.win32\libLwf.vcxproj" could not be found.
Is there any way to compile the project? Thanks.

**Comment by splhack** [comment]
Could you try the latest master?
